[project]
name = "user_microservice"
version = "0.1.0"
description = "User management microservice for Fit Company"
requires-python = ">=3.10"
dependencies = [
    "Flask",
    "Flask-JWT-Extended",
    "SQLAlchemy",
    "psycopg2-binary",
    "pydantic[email]",
    "requests"
] 